### PR TITLE
Feature/user transaction views

### PR DESCRIPTION
**Pull request by cimafrancamae**
- Fix buy/sell button and transaction functionalities
- Fix toast rendering on create transaction
- Added Portfolio Overview on user feed

### CODE REVIEW

**Comment by TyJacalan** [comment]
Hi Mae!

Can you check if the nav buttons are working? They seem to be blocked by this element:
```
<div x-transition:enter="transition-opacity ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-[-10px]" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition-opacity ease-in duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform translate-y-[-10px]" class="w-full fixed top-0 left-0 z-50 p-4 __web-inspector-hide-shortcut__">
  ...
</div>
```

**Comment by TyJacalan** [comment]
The buy/sell button doesn't render anything

**Comment by cimafrancamae** [comment]
> Hi Mae!
> 
> Can you check if the nav buttons are working? They seem to be blocked by this element:
> 
> ```
> <div x-transition:enter="transition-opacity ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-[-10px]" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition-opacity ease-in duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform translate-y-[-10px]" class="w-full fixed top-0 left-0 z-50 p-4 __web-inspector-hide-shortcut__">
>   ...
> </div>
> ```

Hello, the buttons are working... those transitions are not but I forgot to remove them, sorry. I already replaced them on my next commit

**Comment by cimafrancamae** [comment]
> The buy/sell button doesn't render anything

It does render but it's slow. I already fixed it though. The reason was the unnecessary "before_actions" and "include" in the controller.

**Comment by cimafrancamae** [comment]
I couldn't sync my newest commit though due to this. Please advice...

```
> git pull --tags origin feature/user-transaction-views
From https://github.com/TyJacalan/trading-app
 * branch            feature/user-transaction-views -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

```

**Comment by cimafrancamae** [comment]
> I couldn't sync my newest commit though due to this. Please advice...
> 
> ```
> > git pull --tags origin feature/user-transaction-views
> From https://github.com/TyJacalan/trading-app
>  * branch            feature/user-transaction-views -> FETCH_HEAD
> hint: You have divergent branches and need to specify how to reconcile them.
> hint: You can do so by running one of the following commands sometime before
> hint: your next pull:
> hint: 
> hint:   git config pull.rebase false  # merge (the default strategy)
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint: 
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> fatal: Need to specify how to reconcile divergent branches.
> ```

This has been resolved.

**Pull request merged**
